env:
  TERM: xterm-256color

window:
  padding:
    x: 0
    y: 0
  dynamic_padding: false

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    style: Regular
  bold_italic:
    style: Italic
  size: 14.0

import:
  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
