window:
  padding:
    x: 3
    y: 3
  dynamic_padding: false

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraLight
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraLight
  bold_italic:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraLight Italic
  size: 16.0

key_bindings:
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word

import:
  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
