version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./init-db.sql:/docker-entrypoint-initdb.d/schema.sql"
    expose:
      - "3306"
    tmpfs:
      - /var/lib/mysql