version: "3"

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg13
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always

